function emailSend() {
    Email.send({
        Host: "smtp.gmail.com",
        Username: "chetanmustoor14@gmail.com",
        Password: "6AFE2DCE6AEE3F0DB34E631A534E362EDF1D",// Use the App Password generated by Gmail
        To: 'chetanmustoor14@gmail.com',
        From: document.getElementById('email').value,
        Subject: document.getElementById('subject').value,
        Body: "Name: " + document.getElementById('name').value 
        + "<br/>Email: " + document.getElementById('email').value
        + "<br/>Subject: " + document.getElementById('subject').value
        + "<br/>Message: " + document.getElementById('message').value
    }).then(
        message => {
            if (message == 'OK') {
                swal("Successful", "Email sent successfully!", "success");
            } else {
                console.log(message);  // log error for debugging
                swal("Error", "Failed to send the email. Please try again.", "error");
            }
        }
    ).catch(error => {
        console.log(error);  // Catch any errors for debugging
        swal("Error", "Failed to send the email due to an error.", "error");
    });
}







// function emailSend() {
//     Email.send({
//         Host: "smtp.gmail.com",
//         Username: "chetanmustoor14@gmail.com",
//         Password: "6AFE2DCE6AEE3F0DB34E631A534E362EDF1D",
//         To: 'chetanmustoor14@gmail.com',
//         From: document.getElementById('email').value,
//         Subject: document.getElementById('subject').value,
//         Body: "Name: " + document.getElementById('name').value 
//         + "<br/>Email: " + document.getElementById('email').value
//         + "<br/>Subject: " + document.getElementById('subject').value
//         + "<br/>Message: " + document.getElementById('message').value
//     }).then(
//         message => {
//             if (message == 'OK') {
//                 swal("Successful", "Email sent successfully!", "success");
//             } else {
//                 console.log(message);  // log error for debugging
//                 swal("Error", "Failed to send the email. Please try again.", "error");
//             }
//         }
//     );
// }






